apiVersion: v1
kind: Service
metadata:
  name: example-rabbitmq
spec:
  type: ClusterIP
  selector:
    app: example-rabbitmq
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http